### ISSUE TITLE
Working on section 07 - hardware

### ISSUE THREAD

**Issue by InfoHunter** [riboseinc/rfc-crypto-sm3#4]
Is there anyone works on this? If not, I am going to do so...

**Comment by InfoHunter** [comment]
Or, still this section is necessary to be included into the draft? Ping @ronaldtse

**Comment by ronaldtse** [comment]
@InfoHunter I feel that it's not really necessary:

* Performance it is very time-dependent -- performance generally gets better over time.
* The reference code they used is not optimized, yet they are comparing with a heavily optimized OpenSSL.

Maybe we can replace this with a short section in "Introduction", just to say that it has been implemented in software (OpenSSL, Botan, etc) and hardware (ASIC / FPGA). I think the unique thing about SM3 is its minimal usage of gates/slices in hardware realization.

**Comment by InfoHunter** [comment]
OK, that's fine

**Comment by InfoHunter** [comment]
Just skip the hardware section as discussed earlier.
