### ISSUE TITLE
OSCCA's name

### ISSUE THREAD

**Issue by InfoHunter** [riboseinc/rfc-crypto-sm3#7]
As previously discussed with @ronaldtse through email, should the name OSCCA be changed to SCA?

Besides, the current OSCCA's full name is not correct in our document, currently it's `Organization of State Commercial Administration of China`, which should be `Office of State Commercial Cryptography Administration`

**Comment by InfoHunter** [comment]
And this is the full name for SCA: `State Cryptography Administration`

**Comment by ronaldtse** [comment]
Indeed we should update it now they have rebranded. And we need to change the draft's name... 😓
